version: "3"

services:
  poky-base:
    build:
      context: ./poky
      dockerfile: Dockerfile
      target: poky-base
    volumes:
      - ./caches/dl:/mnt/dl-cache
      - ./caches/sstate:/mnt/sstate-cache
      - ./data:/work
      - /srv/nfs:/srv/nfs
      - /srv/tftp:/srv/tftp
      - /srv/ftp:/srv/ftp
    tty: true
    stdin_open: true

  poky-arm:
    extends:
      service: poky-base
    build:
      target: poky-arm
    hostname: poky-arm

  poky-qemuarm:
    extends:
      service: poky-arm
    environment:
      - MACHINE=qemuarm
    hostname: poky-qemuarm

  poky-x86:
    extends:
      service: poky-base
    build:
      target: poky-x86
    hostname: poky-x86

  poky-qemux86:
    extends:
      service: poky-x86
    environment:
      - MACHINE=qemux86
    hostname: poky-qemux86

  poky-qemux86-64:
    extends:
      service: poky-x86
    environment:
      - MACHINE=quemux86-64
    hostname: poky-qemux86-64
