#!/bin/bash

NETBOOT_DIR_TFTP="/srv/tftp"
NETBOOT_DIR_NFS="/srv/nfs"

BUILD_IMAGE=$1

cp $BUILDDIR/tmp/deploy/images/$MACHINE/{zImage *.itb *.bin} $NETBOOT_DIR_TFTP
tar xzpf $BUILDDIR/tmp/deploy/images/$MACHINE/$BUILD_IMAGE-$MACHINE.tar.gz $NETBOOT_DIR_NFS